# permissions for end users to view prometheusoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: prometheusoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prometheus-operator
    app.kubernetes.io/part-of: prometheus-operator
    app.kubernetes.io/managed-by: kustomize
  name: prometheusoperator-viewer-role
rules:
- apiGroups:
  - monitoring.example.com
  resources:
  - prometheusoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.example.com
  resources:
  - prometheusoperators/status
  verbs:
  - get
