apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheusoperator-sample-pvc
  namespace: prometheus-operator-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
